FROM registry.access.redhat.com/ubi8/python-38

# Install dependencies
RUN  python3.8 -m pip install --upgrade pip setuptools \
     && python3.8 -m pip install compliance-trestle==1.2.0 \
     && python3.8 -m pip install python-semantic-release==7.31.4

ENTRYPOINT ["trestle", "-h"]