name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: write
      deployments: none
      id-token: write
      issues: write
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: create-ssp
          repository: RedHatProductSecurity/trestle-demo